version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"
    labels:
      - "kind/cleanup"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      # Ignore Cluster-API as its upgraded manually.
      - dependency-name: "sigs.k8s.io/cluster-api*"
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
      # Ignore k8s and its transitives modules as they are upgraded manually
      # together with controller-runtime.
      - dependency-name: "k8s.io/*"
      - dependency-name: "go.etcd.io/*"
      - dependency-name: "google.golang.org/grpc"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"
    labels:
      - "kind/cleanup"
    groups:
      dependencies:
        patterns:
          - "*"

  # Enable version updates for Go tools
  - package-ecosystem: "gomod"
    directory: "/hack/tools"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"
    labels:
      - "kind/cleanup"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      # Ignore Cluster-API as its upgraded manually.
      - dependency-name: "sigs.k8s.io/cluster-api*"
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
      # Ignore k8s and its transitives modules as they are upgraded manually
      # together with controller-runtime.
      - dependency-name: "k8s.io/*"
      # Ignore controller-tools as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-tools"

  - package-ecosystem: "docker"
    directory: "/hack/tools"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"
    labels:
      - "kind/cleanup"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"
    labels:
      - "kind/cleanup"
    groups:
      dependencies:
        patterns:
          - "*"
