version: 2.1


jobs:
  build:
    machine:
      image: "ubuntu-2204:2022.10.2"
    environment:
      ALL_ARCH: "amd64 arm64"
      REGISTRY_QUAY: quay.io/giantswarm
      REGISTRY_CHINA: registry-intl.cn-shanghai.aliyuncs.com/giantswarm
    steps:
      - checkout
      - run:
          name: Build the CAPI docker images
          command: |
            for registry in $REGISTRY_QUAY $REGISTRY_CHINA; do
              make docker-build-all ALL_ARCH="$ALL_ARCH" TAG=$CIRCLE_SHA1 REGISTRY=$registry
            done
      - run:
          name: Push to quay
          command: |
            docker login --username $QUAY_USERNAME --password $QUAY_PASSWORD quay.io

            make docker-push-all ALL_ARCH="$ALL_ARCH" TAG=$CIRCLE_SHA1 REGISTRY=$REGISTRY_QUAY
            if [[ -n $CIRCLE_TAG ]]; then docker tag quay.io/giantswarm/cluster-api-aws-controller:$CIRCLE_SHA1 quay.io/giantswarm/cluster-api-aws-controller:$CIRCLE_TAG && docker push quay.io/giantswarm/cluster-api-aws-controller:$CIRCLE_TAG; fi

      # Waiting for https://gigantic.slack.com/archives/C3C7ZQXC1/p1674714600715149
      # ---
      # - run:
      #     name: Push to aliyun
      #     command: |
      #       docker login --username $ALIYUN_USERNAME --password $ALIYUN_PASSWORD registry-intl.cn-shanghai.aliyuncs.com

      #       make docker-push-all ALL_ARCH="$ALL_ARCH" TAG=$CIRCLE_SHA1 REGISTRY=$REGISTRY_CHINA
      #       if [[ -n $CIRCLE_TAG ]]; then docker tag registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-api-aws-controller:$CIRCLE_SHA1 registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-api-aws-controller:$CIRCLE_TAG && docker push registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-api-aws-controller:$CIRCLE_TAG; fi

workflows:
  version: 2
  build_and_update:
    jobs:
      - build:
          context:
            - architect
          filters:
            tags:
              only: /^v.*/
