version: 2.1


jobs:
  build:
    machine:
      image: "ubuntu-2204:2022.10.2"
    environment:
      ALL_ARCH: "amd64 arm64"
      REGISTRY_QUAY: quay.io/giantswarm
      REGISTRY_CHINA: registry-intl.cn-shanghai.aliyuncs.com/giantswarm
    steps:
      - checkout
      - run:
          name: Build the CAPI docker images
          command: |
            # Add release manifest to our Docker image. These are used by
            # https://github.com/giantswarm/cluster-api-provider-aws-app to fetch CRD manifests. We don't create
            # GitHub releases as https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases, so our fork
            # uses this alternative way of providing the files.
            awk '
                /RUN.*go-build/ {
                    print "RUN make release-manifests RELEASE_TAG=REPLACE_ME_RELEASE_TAG REGISTRY=REPLACE_ME_REGISTRY"
                }
                /COPY --from=builder \/workspace\/manager/ {
                    print "COPY --from=builder /workspace/out/infrastructure-components.yaml /for-cluster-api-provider-aws-app-only/infrastructure-components.yaml"
                }

                { print }
                ' Dockerfile >/tmp/Dockerfile && mv /tmp/Dockerfile Dockerfile
            # `make release-manifests` needs `config/`, `hack/`, `Makefile` and probably more, so just copy
            # everything into the Docker context
            rm .dockerignore

            for registry in $REGISTRY_QUAY $REGISTRY_CHINA; do
              make docker-build-all ALL_ARCH="$ALL_ARCH" TAG=$CIRCLE_SHA1 REGISTRY=$registry

              if [ -n "$CIRCLE_TAG" ]; then
                echo "Building tag $CIRCLE_TAG"
                make docker-build-all ALL_ARCH="$ALL_ARCH" TAG="$CIRCLE_TAG" REGISTRY=$registry
              fi
            done
      - run:
          name: Push to quay
          command: |
            docker login --username $QUAY_USERNAME --password $QUAY_PASSWORD quay.io

            make docker-push-all ALL_ARCH="$ALL_ARCH" TAG=$CIRCLE_SHA1 REGISTRY=$REGISTRY_QUAY

            if [ -n "$CIRCLE_TAG" ]; then
              echo "Pushing tag $CIRCLE_TAG"
              make docker-push-all ALL_ARCH="$ALL_ARCH" TAG="$CIRCLE_TAG" REGISTRY=$REGISTRY_QUAY
            fi

      # Waiting for https://gigantic.slack.com/archives/C3C7ZQXC1/p1674714600715149
      # ---
      # - run:
      #     name: Push to aliyun
      #     command: |
      #       docker login --username $ALIYUN_USERNAME --password $ALIYUN_PASSWORD registry-intl.cn-shanghai.aliyuncs.com

      #       make docker-push-all ALL_ARCH="$ALL_ARCH" TAG=$CIRCLE_SHA1 REGISTRY=$REGISTRY_CHINA

      #       if [ -n "$CIRCLE_TAG" ]; then
      #         echo "Pushing tag $CIRCLE_TAG"
      #         make docker-push-all ALL_ARCH="$ALL_ARCH" TAG="$CIRCLE_TAG" REGISTRY=$REGISTRY_CHINA
      #       fi

workflows:
  version: 2
  build_and_update:
    jobs:
      - build:
          context:
            - architect
          filters:
            tags:
              only: /^v.*/
