version: 2.1


jobs:
  build:
    machine:
      image: "ubuntu-2004:202010-01"
    steps:
      - checkout
      - run:
          name: Build the CAPI docker images
          command: |
            make docker-build
      - run:
          name: Login to quay
          command: |
            docker login --username $QUAY_USERNAME --password $QUAY_PASSWORD quay.io
      - run:
          name: Push images to quay
          command: |
            docker push quay.io/$CIRCLE_PROJECT_USERNAME/cluster-api-aws-controller:${CIRCLE_TAG:-$CIRCLE_SHA1}
            docker push quay.io/$CIRCLE_PROJECT_USERNAME/eks-bootstrap-controller:${CIRCLE_TAG:-$CIRCLE_SHA1}
            docker push quay.io/$CIRCLE_PROJECT_USERNAME/eks-controlplane-controller:${CIRCLE_TAG:-$CIRCLE_SHA1}
      - run:
          name: Login to aliyun
          command: |
            docker login --username $ALIYUN_USERNAME --password $ALIYUN_PASSWORD registry-intl.cn-shanghai.aliyuncs.com
      - run:
          name: Push images to aliyun
          command: |
            docker push registry-intl.cn-shanghai.aliyuncs.com/$CIRCLE_PROJECT_USERNAME/cluster-api-aws-controller:${CIRCLE_TAG:-$CIRCLE_SHA1}
            docker push registry-intl.cn-shanghai.aliyuncs.com/$CIRCLE_PROJECT_USERNAME/eks-bootstrap-controller:${CIRCLE_TAG:-$CIRCLE_SHA1}
            docker push registry-intl.cn-shanghai.aliyuncs.com/$CIRCLE_PROJECT_USERNAME/eks-controlplane-controller:${CIRCLE_TAG:-$CIRCLE_SHA1}

workflows:
  version: 2
  build_and_update:
    jobs:
      - build:
          context:
            - architect
          # Trigger the job also on git tag.
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+)?$/
